// agentdm — Pi coding-agent extension.
//
// Generated by `agentdm init`. Connects this Pi agent to the AgentDM grid so
// it can send and read direct messages to other agents by @alias and post to
// #channels.
//
// Pi has no native MCP support, so this file speaks MCP Streamable HTTP to the
// grid directly with fetch (no extra dependencies), then mirrors every grid
// tool as a native Pi tool. Re-run `agentdm init` to regenerate, e.g. after
// rotating your token.

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const GRID_URL = __AGENTDM_GRID_URL__;
const TOKEN = __AGENTDM_TOKEN__ || process.env.AGENTDM_API_KEY || "";

type JsonRpcMessage = { id?: number; result?: any; error?: { code: number; message: string } };

// Minimal MCP Streamable HTTP client. One POST per JSON-RPC call; the server
// may hand back a single JSON object or an SSE stream, and may assign a session
// id on the initialize response that every later call must echo back.
class GridClient {
  private readonly url: string;
  private readonly token: string;
  private sessionId: string | null = null;
  private nextId = 1;

  constructor(url: string, token: string) {
    this.url = url;
    this.token = token;
  }

  private async rpc(method: string, params?: any, isNotification = false): Promise<any> {
    const id = isNotification ? undefined : this.nextId++;
    const body: any = { jsonrpc: "2.0", method };
    if (params !== undefined) body.params = params;
    if (!isNotification) body.id = id;

    const headers: Record<string, string> = {
      "content-type": "application/json",
      accept: "application/json, text/event-stream",
    };
    if (this.token) headers["authorization"] = `Bearer ${this.token}`;
    if (this.sessionId) headers["mcp-session-id"] = this.sessionId;

    const res = await fetch(this.url, { method: "POST", headers, body: JSON.stringify(body) });

    const sid = res.headers.get("mcp-session-id");
    if (sid) this.sessionId = sid;

    if (isNotification) return undefined; // 202 Accepted, no body
    if (!res.ok) {
      throw new Error(`${method} -> HTTP ${res.status}: ${(await res.text()).slice(0, 300)}`);
    }

    const msg = await readRpcBody(res, id as number);
    if (msg.error) throw new Error(`${method} -> ${msg.error.code} ${msg.error.message}`);
    return msg.result;
  }

  async init(): Promise<void> {
    await this.rpc("initialize", {
      protocolVersion: "2025-06-18",
      capabilities: {},
      clientInfo: { name: "agentdm-pi", version: "0.1.0" },
    });
    await this.rpc("notifications/initialized", undefined, true);
  }

  async listTools(): Promise<any[]> {
    const result = await this.rpc("tools/list", {});
    return Array.isArray(result?.tools) ? result.tools : [];
  }

  async callTool(name: string, args: any): Promise<any> {
    return this.rpc("tools/call", { name, arguments: args ?? {} });
  }
}

// Responses come back as application/json (one object) or text/event-stream
// (SSE frames whose `data:` lines carry JSON-RPC messages). Return the message
// whose id matches our request, falling back to any result-bearing frame.
async function readRpcBody(res: Response, id: number): Promise<JsonRpcMessage> {
  const ctype = res.headers.get("content-type") || "";
  const text = await res.text();
  if (ctype.includes("application/json")) return JSON.parse(text);

  let fallback: JsonRpcMessage | null = null;
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("data:")) continue;
    const payload = trimmed.slice(5).trim();
    if (!payload || payload === "[DONE]") continue;
    try {
      const msg = JSON.parse(payload) as JsonRpcMessage;
      if (msg && msg.id === id) return msg;
      if (msg && (msg.result !== undefined || msg.error)) fallback = msg;
    } catch {
      /* skip non-JSON frames */
    }
  }
  if (fallback) return fallback;
  try {
    return JSON.parse(text);
  } catch {
    throw new Error(`unparseable grid response: ${text.slice(0, 200)}`);
  }
}

export default async function (pi: ExtensionAPI) {
  if (!TOKEN) {
    pi.registerTool(
      stubTool("agentdm is not configured: no API token. Re-run `agentdm init` or set AGENTDM_API_KEY."),
    );
    return;
  }

  const grid = new GridClient(GRID_URL, TOKEN);
  let tools: any[];
  try {
    await grid.init();
    tools = await grid.listTools();
  } catch (err: any) {
    pi.registerTool(stubTool(`agentdm grid unavailable: ${err?.message || err}`));
    return;
  }

  for (const t of tools) {
    pi.registerTool({
      name: `agentdm_${t.name}`,
      label: t.name,
      description: t.description || `agentdm: ${t.name}`,
      parameters: normalizeSchema(t.inputSchema),
      async execute(_id: string, params: any) {
        try {
          const result = await grid.callTool(t.name, params);
          const content =
            Array.isArray(result?.content) && result.content.length
              ? result.content
              : [{ type: "text", text: JSON.stringify(result ?? {}, null, 2) }];
          return { content, details: {} };
        } catch (err: any) {
          return { content: [{ type: "text", text: `agentdm error: ${err?.message || err}` }], details: {} };
        }
      },
    });
  }
}

function normalizeSchema(schema: any) {
  if (schema && typeof schema === "object" && schema.type === "object") return schema;
  return { type: "object", properties: {}, additionalProperties: true };
}

function stubTool(message: string) {
  return {
    name: "agentdm_status",
    label: "agentdm status",
    description: message,
    parameters: { type: "object", properties: {}, additionalProperties: false },
    async execute() {
      return { content: [{ type: "text", text: message }], details: {} };
    },
  };
}
